version: '3'

services:
  hc:
    build: .
    environment:
      HOSTS: >
        http://test-server1:3030/healthcheck,
        http://test-server2:3031/healthcheck,
        http://test-server3:3032/healthcheck
      RETRIES: 10
      INTERVAL: 2s
      TIMEOUT: 3s
    depends_on:
      - test-server1
      - test-server2
      - test-server3

  test-server1:
    build: 
      context: .
      dockerfile: Dockerfile-testserver
    environment:
      - PORT=3030
      - FAIL_COUNT=4
      - RESPONSE_DELAY=2500
    # Can't use a typical healthcheck for distroless containers.
    # The following won't work:
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  test-server2:
    build: 
      context: .
      dockerfile: Dockerfile-testserver
    environment:
      - PORT=3031
      - RESPONSE_DELAY=1500
      - FAIL_COUNT=9

  test-server3:
    build: 
      context: .
      dockerfile: Dockerfile-testserver
    environment:
      - PORT=3032
      - RESPONSE_DELAY=4000
      - FAIL_COUNT=5
